expensetrack/expense/urls.py
from django.urls import path
from . import views

app_name = 'expenses'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.create, name='create'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('destroy/<int:pk>', views.delete, name='destroy'),
]

expensetrack/expensetrack/urls.py
from . import views

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense.urls')),
    path('about/', views.about, name='about'),
]

expensetrack/expense/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Expense(models.Model):
    title = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.title} - {self.amount}"

expensetrack/expense/forms.py
from django import forms 
from .models import Expense

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['title', 'amount', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'p-2 border border-gray-200 block w-full rounded-md shadow-md'}),
            'amount': forms.NumberInput(attrs={'class': 'p-2 border border-gray-200 block w-full rounded-md shadow-md'}),
            'description': forms.Textarea(attrs={'class': 'p-2 border border-gray-200 block w-full rounded-md shadow-md', 'rows': 3}),
        }
    
    # def clean_amount(self):
    #     amount = self.cleaned_data.get('amount')
    #     if amount <= 0:
    #         raise forms.ValidationError("Amount must be greater than zero.")
    #     return amount

expensetrack/expense/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Expense
from .forms import ExpenseForm
from django.db.models import Sum
from django.utils import timezone

# Create your views here.
def index (request):
    expenses = Expense.objects.all().order_by('-id')
    today_total_expenses = Expense.objects.filter(created_at=timezone.now().date()).aggregate(total=Sum('amount'))['total'] or 0
    current_week_total_expenses = Expense.objects.filter(created_at__week=timezone.now().isocalendar()[1]).aggregate(total=Sum('amount'))['total'] or 0
    current_month_total_expenses = Expense.objects.filter(created_at__month=timezone.now().month).aggregate(total=Sum('amount'))['total'] or 0

    stats = {
        'today_total': today_total_expenses,
        'current_week_total': current_week_total_expenses,
        'current_month_total': current_month_total_expenses,
    }

    return render(request, 'expense/index.html', {'expenses': expenses, 'stats': stats})

def create (request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            form.user = request.user
            form.save()

            # Redirect to the index page after saving the form
            return redirect('expenses:index')
    else:
        form = ExpenseForm()
    return render(request, 'expense/create.html', {'form': form})

def edit (request, pk):
    expense = get_object_or_404(Expense, pk=pk)

    if request.method == 'POST':
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()

            # Redirect to the index page after saving the form
            return redirect('expenses:index')
    else:
        form = ExpenseForm(instance=expense)
    return render(request, 'expense/edit.html', {'form': form})

def delete (request, pk):
    expense = get_object_or_404(Expense, pk=pk)

    if request.method == 'POST':
        expense.delete()

    # Redirect to the index page after saving the form
    return redirect('expenses:index')     

expensetrack/expensetrack/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request, 'about.html')

expensetrack/expense/templates/expense/create.html
{% extends "layout.html" %}

{% block title %} Adicionar gasto {% endblock %}

{% block content %}
<h1 class="text-2xl font-bold uppercase">Adicionar gasto</h1>
<p class="mt-4">Preencha os campos abaixo</p>

<div>
    <form method="post" class="mt-6">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-sky-500 text-white px-4 py-2 rounded hover:bg-sky-600">
        Adicionar
        </button>
    </form>
</div>

{% endblock %}

expensetrack/expense/templates/expense/edit.html
{% extends "layout.html" %}

{% block title %} Adicionar gasto {% endblock %}

{% block content %}
<h1 class="text-2xl font-bold uppercase">Editar registo</h1>
<p class="mt-4">Preencha os campos abaixo</p>

<div>
    <form method="post" class="mt-6">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-sky-500 text-white px-4 py-2 rounded hover:bg-sky-600">
        Adicionar
        </button>
    </form>
</div>

{% endblock %}

expensetrack/expense/templates/expense/index.html
{% extends "layout.html" %} 
{% block title %} 
Controle de Gastos App 
{% endblock %} 

{% block content %}
<div class="bg-gradient-to-r via-white from-sky-400 to-white p-4 md:p-8 rounded-xl shadow-md flex flex-col md:flex-row items-center justify-between space-y-5 md:space-y-0 md:space-x-4">

  <div>
    <h1 class="text-2xl font-bold uppercase">Lista de gastos</h1>
    <p class="mt-4">Bemvindo ao seu app de controle de gastos</p>
    <p class="mt-2">Aqui podes gerir as suas finanças com eficiência.</p>
  </div>

  <div class="flex flex-col items-center space-y-4">
      <div class="w-full text-xl flex flex-col items-center justify-center border border-gray-200 rounded-md p-2">
        <span class="text-sky-500  font-bold">Total de gastos hoje:</span>
        <span class="text-gray-800 text-3xl">{{ stats.today_total|floatformat:2 }} Kz</span>
      </div>

       <div class="text-xl flex flex-col items-center justify-center border border-gray-200 rounded-md p-2">
        <span class="text-sky-500  font-bold">Total de gastos esta semana:</span>
        <span class="text-gray-800 text-3xl">{{ stats.current_week_total|floatformat:2 }} Kz</span>
      </div>

  </div>

</div>

<div class="mt-7 w-full overflow-x-auto">
  <table class="w-full">
    <thead>
      <tr class="bg-gray-200">
        <th>ID</th>
        <th>Título</th>
        <th>Valor</th>
        <th>Açoes</th>
      </tr>
    </thead>
    <tbody>

      {% for expense in expenses %}
      <tr class="odd:bg-gray-100 even:bg-white">
        <td>{{ expense.id }}</td>
        <td>{{ expense.title }}</td>
        <td>{{ expense.amount }}</td>
        <td>
          <div class="space-x-2 flex">
            <a href="{% url 'expenses:edit' expense.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
              </svg>
            </a>
            <form action="{% url 'expenses:destroy' expense.id %}" method="post">
              {% csrf_token %}
              <button type="submit" onclick="return confirm('Tem certeza?')" class="text-red-500 hover:text-red-700">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                </svg>
              </button>
            </form>
          </div>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4" class="text-center">
          <div class="icon text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 mx-auto">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
            </svg>
          </div>
          <div class="text-center">No records found! Start adding now!</div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

expensetrack/templates/about.html
{% extends "layout.html" %}

{% block title %} Controle de Gastos App {% endblock %}

{% block content %}
<h1 class="text-2xl font-bold uppercase">Controle de Gastos App</h1>
<p class="mt-2">O Controle de Gastos App é um sistema simples e eficiente que te ajuda a gerir as suas finanças.</p>
{% endblock %}

expensetrack/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Home {% endblock %} - Expenses track app</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
      rel="stylesheet"
    />

    <style>
      
        td, th {
          padding: 10px;
          text-align: left;
        }

        form p {
          margin: 12px 0;
        }
      
    </style>
  </head>
  <body>
    <div class="flex flex-col justify-between min-h-screen">
      <div class="border-b border-gray-200 bg-white shadow-sm">
        <nav
          class="flex items-center justify-between w-full max-w-7xl mx-auto px-4"
        >
          <a href="/" class="text-xl font-bold text-clifford text-sky-500 py-5">
            Expenses App
          </a>

          <div class="flex items-center space-x-4">
            <a class="text-sky-500 hover:text-sky-700"
              href="{% url 'expenses:index' %}"
              class="px-4 py-2"
              >Gastos</a
            >
            <a class="text-sky-500 hover:text-sky-700"
              href="{% url 'expenses:create' %}"
              class="px-4 py-2"
              >Adicionar</a
            >

            <a class="text-sky-500 hover:text-sky-700"
              href="{% url 'about' %}"
              class="px-4 py-2"
              >Sobre</a
            >

          </div>
        </nav>
      </div>

      <div class="flex-grow">
        <div class="w-full max-w-7xl mx-auto px-4 my-10">
          {% block content %} {% endblock %}
        </div>
      </div>

      <div class="border-t border-gray-200 bg-gray-100 py-10">
        <div class="w-full max-w-7xl mx-auto px-4">
          &copy; 2025 - Julian F. Kataleko
        </div>
      </div>
    </div>
  </body>
</html>